services:
  product-standard-app:
    build: .
    command: python Расчет_эталона.py
    volumes:
      - ./src:/src
      - ./static:/static
    container_name: product-standard-app
    tty: true
    env_file: ".env"
    depends_on:
      - product-standard-db

  product-standard-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"
    container_name: product-standard-db
    volumes:
      - product-standard-db-volume:/var/lib/postgresql/data/
      - ./static:/static

volumes:
  product-standard-db-volume: